# Generated by Django 4.0.3 on 2022-05-02 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('fulfilled', 'Fulfilled')], default='incomplete', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=250, unique_for_date='time')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
