# Generated by Django 4.0.3 on 2022-04-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0004_alter_job_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homeservice.listing'),
        ),
    ]
