# Generated by Django 4.0.3 on 2022-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0005_alter_job_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='listing',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='specialty',
        ),
    ]
