# Generated by Django 4.0.3 on 2022-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0006_clientaccount_rename_listing_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='jobs',
            field=models.ManyToManyField(to='homeservice.job'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='client_id',
            field=models.IntegerField(default=1),
        ),
    ]
