# Generated by Django 4.0.3 on 2022-04-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0009_alter_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='client_id',
        ),
    ]
